services:
  nginx:
    build:
      context: ./Nginx
    ports:
      - "80:80"
    networks:
      - my-network
    depends_on:
      - funcionario
      - estoque
      - renatos-barbershop

  funcionario:
    image: pedrop8/servico-funcionario
    container_name: funcionario
    ports:
      - "8080:8080"
    networks:
      - my-network

  db:
    image: postgres:14.2-alpine
    container_name: db-estoque22
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: microservico_estoque_development
      POSTGRES_USER: vinicius
      POSTGRES_PASSWORD: 123
    ports:
      - "5434:5433"
    networks:
      - my-network

  estoque:
    container_name: estoque
    image: viniciusr21/mc-rails123:atualizado
    env_file: .env
    command: "bundle exec rails s -p 3001 -b '0.0.0.0'"
    environment:
      DB_HOST: db
      DB_NAME: microservico_estoque_development
      DB_USERNAME: vinicius
      DB_PASSWORD: 123
    volumes:
      - .:/app:cached
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - my-network

  postgres:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5435"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: renatos_barbershop_db
    volumes:
      - postgres_data_luis_felipe:/var/lib/postgresql/data
    networks:
      - my-network

  renatos-barbershop:
    image: luizfelipetorresfarias/renatos-barbershop:latest
    depends_on:
      - postgres
    env_file:
      - .env-dockerfile
    ports:
      - "8081:8081"
    networks:
      - my-network

  db-loyalty:
    image: postgres:15.5-alpine
    ports:
      - "5436:5436"
    volumes:
      - ../tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: barber-loyalty
      POSTGRES_PASSWORD: password
      POSTGRES_DB: barber-loyalty-dev
    networks:
      - my-network

  loyalty:
    image: gcarvalhof/barber-loyalty-inf-016:0.0.2
    stdin_open: true
    tty: true
    volumes:
      - ..:/app
    ports:
      - "3000:3000"
    depends_on:
      - db-loyalty
    environment:
      USERNAME: barber-loyalty
      PASSWORD: password
      HOSTNAME: db-loyalty
      DB_PORT: 5436
      DB_NAME: barber-loyalty-dev
    networks:
      - my-network

networks:
  my-network:

volumes:
  postgres_data:
  postgres_data_luis_felipe:
